[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 